version: '3'


services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=fleet_management
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=apipassword

    healthcheck:
      test: "pg_isready -U api_user"
      interval: 5s
  web:
    build: .
    command: >
      sh -c "python /nuvolar_fleet_project/manage.py migrate &&
             python /nuvolar_fleet_project/manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=fleet_management
      - DB_USER=api_user
      - DB_PASS=apipassword
      - DEBUG=1
    volumes:
      - .:/nuvolar_fleet_project
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
