# Generated by Django 4.2 on 2023-04-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_api', '0002_rename_arrival_time_flight_arrival_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='aircraft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_api.aircraft', unique=True),
        ),
    ]
