# Generated by Django 4.2 on 2023-04-12 16:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_api', '0002_alter_flight_departure_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departure_datetime',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2023, 4, 12, 16, 4, 17, 449484, tzinfo=datetime.timezone.utc), message='Depature datetime cannot be in the past.')]),
        ),
    ]
